Fix pluginVersion for unreleased version
Changelog v2.0.0 requires matching pluginVersion in CHANGELOG.md.

I got error:
```
1 problem was found storing the configuration cache.
- Task `:patchPluginXml` of type `org.jetbrains.intellij.tasks.PatchPluginXmlTask`: value 'map(java.lang.String provider(?) check-type())' failed to unpack provider
(snip)
> org.jetbrains.changelog.exceptions.MissingVersionException: Version is missing: any
```